// ===================================================
// Enhanced PRISM MDP Model (Generated by pat2prism)
// Optimized for Security Protocol Verification
// ===================================================

mdp

// ===== Configuration Parameters =====
const double p_flip = 0.02;  // Channel error probability
const int MAX_NONCE = 10000;

// ===== Message Type Encoding =====
// Maps message names to integer indices for channel variablesconst int MSG_NO_MSG = 0;  // NO_MSGconst int MSG_CoAP_POST = 1;  // CoAP_POSTconst int MSG_CoAP_ACK = 2;  // CoAP_ACKconst int MSG_EAP_Request_Identity = 3;  // EAP_Request_Identityconst int MSG_EAP_Response_Identity = 4;  // EAP_Response_Identityconst int MSG_EAP_Request_PSK_M1 = 5;  // EAP_Request_PSK_M1const int MSG_EAP_Response_PSK_M2 = 6;  // EAP_Response_PSK_M2const int MSG_EAP_Request_PSK_M3 = 7;  // EAP_Request_PSK_M3const int MSG_EAP_Response_PSK_M4 = 8;  // EAP_Response_PSK_M4const int MSG_EAP_Success = 9;  // EAP_Success
// ===== Global Variables =====
// Protocol variables (from PAT declarations)global CoAP_ACK_N_C : [0..10000] init 0  // nonce field;global CoAP_ACK_N_P : [0..10000] init 0  // nonce field;global EAP_Response_Identity_ID_P : [0..100] init 0  // ID field;global EAP_Request_PSK_M1_N_S : [0..10000] init 0  // nonce field;global EAP_Request_PSK_M1_ID_S : [0..100] init 0  // ID field;global EAP_Response_PSK_M2_MAC_P : [0..1000] init 0  // MAC field;global EAP_Request_PSK_M3_PCHANNEL : [0..1000] init 0  // message field;global EAP_Request_PSK_M3_MAC_S : [0..1000] init 0  // MAC field;global EAP_Success_MSK : [0..1000] init 0  // message field;
// Channel variables (one per channel)global chan_ComSC : [0..9] init 0;  // Channel ComSCglobal chan_ComCA : [0..9] init 0;  // Channel ComCA
// ===== Process Modules =====
// Process: SmartObject
module SmartObject
  // State variable for SmartObject
  s_SmartObject : [0..10] init 0;

  // Transition 0: sync_ComSC_CoAP_POST
  // Synchronized action: sync_ComSC_CoAP_POST
  [sync_ComSC_CoAP_POST] s_SmartObject=0 ->
    (chan_ComSC' = MSG_CoAP_POST) &
    (s_SmartObject' = 1);

  // Transition 1: sync_ComSC_CoAP_ACK
  // Synchronized action: sync_ComSC_CoAP_ACK
  [sync_ComSC_CoAP_ACK] s_SmartObject=1 ->
    (N_C' = CoAP_ACK_N_C) &
    (chan_ComSC' = MSG_CoAP_ACK) &
    (s_SmartObject' = 2);

  // Transition 2: sync_ComSC_EAP_Request_Identity
  // Synchronized action: sync_ComSC_EAP_Request_Identity
  [sync_ComSC_EAP_Request_Identity] s_SmartObject=2 ->
    (chan_ComSC' = MSG_EAP_Request_Identity) &
    (s_SmartObject' = 3);

  // Transition 3: sync_ComSC_EAP_Response_Identity
  // Synchronized action: sync_ComSC_EAP_Response_Identity
  [sync_ComSC_EAP_Response_Identity] s_SmartObject=3 ->
    (EAP_Response_Identity_ID_P' = ID_P) &
    (chan_ComSC' = MSG_EAP_Response_Identity) &
    (s_SmartObject' = 4);

  // Transition 4: sync_ComSC_EAP_Request_PSK_M1
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M1
  [sync_ComSC_EAP_Request_PSK_M1] s_SmartObject=4 ->
    (N_S' = EAP_Request_PSK_M1_N_S) &
    (ID_S' = EAP_Request_PSK_M1_ID_S) &
    (chan_ComSC' = MSG_EAP_Request_PSK_M1) &
    (s_SmartObject' = 5);

  // Transition 5: sync_ComSC_EAP_Response_PSK_M2
  // Synchronized action: sync_ComSC_EAP_Response_PSK_M2
  [sync_ComSC_EAP_Response_PSK_M2] s_SmartObject=5 ->
    (EAP_Response_PSK_M2_MAC_P' = MAC_P) &
    (chan_ComSC' = MSG_EAP_Response_PSK_M2) &
    (s_SmartObject' = 6);

  // Transition 6: sync_ComSC_EAP_Request_PSK_M3
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M3
  [sync_ComSC_EAP_Request_PSK_M3] s_SmartObject=6 ->
    (MAC_S' = EAP_Request_PSK_M3_MAC_S) &
    (PCHANNEL' = EAP_Request_PSK_M3_PCHANNEL) &
    (chan_ComSC' = MSG_EAP_Request_PSK_M3) &
    (s_SmartObject' = 7);

  // Transition 7: sync_ComSC_EAP_Response_PSK_M4
  // Synchronized action: sync_ComSC_EAP_Response_PSK_M4
  [sync_ComSC_EAP_Response_PSK_M4] s_SmartObject=7 ->
    (chan_ComSC' = MSG_EAP_Response_PSK_M4) &
    (s_SmartObject' = 8);

  // Transition 8: sync_ComSC_EAP_Success
  // Synchronized action: sync_ComSC_EAP_Success
  [sync_ComSC_EAP_Success] s_SmartObject=8 ->
    (MSK' = EAP_Success_MSK) &
    (chan_ComSC' = MSG_EAP_Success) &
    (s_SmartObject' = 9);

  // Terminal state (self-loop)
  [] s_SmartObject=10 -> (s_SmartObject' = 10);

endmodule
// Process: Controller
module Controller
  // State variable for Controller
  s_Controller : [0..17] init 0;

  // Transition 0: sync_ComSC_CoAP_POST
  // Synchronized action: sync_ComSC_CoAP_POST
  [sync_ComSC_CoAP_POST] s_Controller=0 ->
    (chan_ComSC' = MSG_CoAP_POST) &
    (s_Controller' = 1);

  // Transition 1: sync_ComSC_CoAP_ACK
  // Synchronized action: sync_ComSC_CoAP_ACK
  [sync_ComSC_CoAP_ACK] s_Controller=1 ->
    (CoAP_ACK_N_C' = N_C) &
    (chan_ComSC' = MSG_CoAP_ACK) &
    (s_Controller' = 2);

  // Transition 2: sync_ComSC_CoAP_ACK
  // Synchronized action: sync_ComSC_CoAP_ACK
  [sync_ComSC_CoAP_ACK] s_Controller=2 ->
    (N_P' = CoAP_ACK_N_P) &
    (chan_ComSC' = MSG_CoAP_ACK) &
    (s_Controller' = 3);

  // Transition 3: sync_ComSC_EAP_Request_Identity
  // Synchronized action: sync_ComSC_EAP_Request_Identity
  [sync_ComSC_EAP_Request_Identity] s_Controller=3 ->
    (chan_ComSC' = MSG_EAP_Request_Identity) &
    (s_Controller' = 4);

  // Transition 4: sync_ComSC_EAP_Response_Identity
  // Synchronized action: sync_ComSC_EAP_Response_Identity
  [sync_ComSC_EAP_Response_Identity] s_Controller=4 ->
    (ID_P' = EAP_Response_Identity_ID_P) &
    (chan_ComSC' = MSG_EAP_Response_Identity) &
    (s_Controller' = 5);

  // Transition 5: sync_ComCA_EAP_Response_Identity
  // Synchronized action: sync_ComCA_EAP_Response_Identity
  [sync_ComCA_EAP_Response_Identity] s_Controller=5 ->
    (EAP_Response_Identity_ID_P' = ID_P) &
    (chan_ComCA' = MSG_EAP_Response_Identity) &
    (s_Controller' = 6);

  // Transition 6: sync_ComCA_EAP_Request_PSK_M1
  // Synchronized action: sync_ComCA_EAP_Request_PSK_M1
  [sync_ComCA_EAP_Request_PSK_M1] s_Controller=6 ->
    (N_S' = EAP_Request_PSK_M1_N_S) &
    (ID_S' = EAP_Request_PSK_M1_ID_S) &
    (chan_ComCA' = MSG_EAP_Request_PSK_M1) &
    (s_Controller' = 7);

  // Transition 7: sync_ComSC_EAP_Request_PSK_M1
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M1
  [sync_ComSC_EAP_Request_PSK_M1] s_Controller=7 ->
    (EAP_Request_PSK_M1_N_S' = N_S) &
    (EAP_Request_PSK_M1_ID_S' = ID_S) &
    (chan_ComSC' = MSG_EAP_Request_PSK_M1) &
    (s_Controller' = 8);

  // Transition 8: sync_ComSC_EAP_Response_PSK_M2
  // Synchronized action: sync_ComSC_EAP_Response_PSK_M2
  [sync_ComSC_EAP_Response_PSK_M2] s_Controller=8 ->
    (MAC_P' = EAP_Response_PSK_M2_MAC_P) &
    (chan_ComSC' = MSG_EAP_Response_PSK_M2) &
    (s_Controller' = 9);

  // Transition 9: sync_ComCA_EAP_Response_PSK_M2
  // Synchronized action: sync_ComCA_EAP_Response_PSK_M2
  [sync_ComCA_EAP_Response_PSK_M2] s_Controller=9 ->
    (EAP_Response_PSK_M2_MAC_P' = MAC_P) &
    (chan_ComCA' = MSG_EAP_Response_PSK_M2) &
    (s_Controller' = 10);

  // Transition 10: sync_ComCA_EAP_Request_PSK_M3
  // Synchronized action: sync_ComCA_EAP_Request_PSK_M3
  [sync_ComCA_EAP_Request_PSK_M3] s_Controller=10 ->
    (MAC_S' = EAP_Request_PSK_M3_MAC_S) &
    (PCHANNEL' = EAP_Request_PSK_M3_PCHANNEL) &
    (chan_ComCA' = MSG_EAP_Request_PSK_M3) &
    (s_Controller' = 11);

  // Transition 11: sync_ComSC_EAP_Request_PSK_M3
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M3
  [sync_ComSC_EAP_Request_PSK_M3] s_Controller=11 ->
    (EAP_Request_PSK_M3_MAC_S' = MAC_S) &
    (EAP_Request_PSK_M3_PCHANNEL' = PCHANNEL) &
    (chan_ComSC' = MSG_EAP_Request_PSK_M3) &
    (s_Controller' = 12);

  // Transition 12: sync_ComSC_EAP_Response_PSK_M4
  // Synchronized action: sync_ComSC_EAP_Response_PSK_M4
  [sync_ComSC_EAP_Response_PSK_M4] s_Controller=12 ->
    (chan_ComSC' = MSG_EAP_Response_PSK_M4) &
    (s_Controller' = 13);

  // Transition 13: sync_ComCA_EAP_Response_PSK_M4
  // Synchronized action: sync_ComCA_EAP_Response_PSK_M4
  [sync_ComCA_EAP_Response_PSK_M4] s_Controller=13 ->
    (chan_ComCA' = MSG_EAP_Response_PSK_M4) &
    (s_Controller' = 14);

  // Transition 14: sync_ComCA_EAP_Success
  // Synchronized action: sync_ComCA_EAP_Success
  [sync_ComCA_EAP_Success] s_Controller=14 ->
    (MSK' = EAP_Success_MSK) &
    (chan_ComCA' = MSG_EAP_Success) &
    (s_Controller' = 15);

  // Transition 15: sync_ComSC_EAP_Success
  // Synchronized action: sync_ComSC_EAP_Success
  [sync_ComSC_EAP_Success] s_Controller=15 ->
    (chan_ComSC' = MSG_EAP_Success) &
    (s_Controller' = 16);

  // Terminal state (self-loop)
  [] s_Controller=17 -> (s_Controller' = 17);

endmodule
// Process: AAA_Server
module AAA_Server
  // State variable for AAA_Server
  s_AAA_Server : [0..7] init 0;

  // Transition 0: sync_ComCA_EAP_Response_Identity
  // Synchronized action: sync_ComCA_EAP_Response_Identity
  [sync_ComCA_EAP_Response_Identity] s_AAA_Server=0 ->
    (ID_P' = EAP_Response_Identity_ID_P) &
    (chan_ComCA' = MSG_EAP_Response_Identity) &
    (s_AAA_Server' = 1);

  // Transition 1: sync_ComCA_EAP_Request_PSK_M1
  // Synchronized action: sync_ComCA_EAP_Request_PSK_M1
  [sync_ComCA_EAP_Request_PSK_M1] s_AAA_Server=1 ->
    (EAP_Request_PSK_M1_N_S' = N_S) &
    (EAP_Request_PSK_M1_ID_S' = ID_S) &
    (chan_ComCA' = MSG_EAP_Request_PSK_M1) &
    (s_AAA_Server' = 2);

  // Transition 2: sync_ComCA_EAP_Response_PSK_M2
  // Synchronized action: sync_ComCA_EAP_Response_PSK_M2
  [sync_ComCA_EAP_Response_PSK_M2] s_AAA_Server=2 ->
    (MAC_P' = EAP_Response_PSK_M2_MAC_P) &
    (chan_ComCA' = MSG_EAP_Response_PSK_M2) &
    (s_AAA_Server' = 3);

  // Transition 3: sync_ComCA_EAP_Request_PSK_M3
  // Synchronized action: sync_ComCA_EAP_Request_PSK_M3
  [sync_ComCA_EAP_Request_PSK_M3] s_AAA_Server=3 ->
    (EAP_Request_PSK_M3_MAC_S' = MAC_S) &
    (EAP_Request_PSK_M3_PCHANNEL' = PCHANNEL) &
    (chan_ComCA' = MSG_EAP_Request_PSK_M3) &
    (s_AAA_Server' = 4);

  // Transition 4: sync_ComCA_EAP_Response_PSK_M4
  // Synchronized action: sync_ComCA_EAP_Response_PSK_M4
  [sync_ComCA_EAP_Response_PSK_M4] s_AAA_Server=4 ->
    (chan_ComCA' = MSG_EAP_Response_PSK_M4) &
    (s_AAA_Server' = 5);

  // Transition 5: sync_ComCA_EAP_Success
  // Synchronized action: sync_ComCA_EAP_Success
  [sync_ComCA_EAP_Success] s_AAA_Server=5 ->
    (EAP_Success_MSK' = MSK) &
    (chan_ComCA' = MSG_EAP_Success) &
    (s_AAA_Server' = 6);

  // Terminal state (self-loop)
  [] s_AAA_Server=7 -> (s_AAA_Server' = 7);

endmodule
// Process: System
module System
  // State variable for System
  s_System : [0..4] init 0;

  // Transition 0: call_SmartObject
  // Function call: call_SmartObject (TODO: implement logic)
  [] s_System=0 ->
    (s_System' = 1);

  // Transition 1: call_Controller
  // Function call: call_Controller (TODO: implement logic)
  [] s_System=1 ->
    (s_System' = 2);

  // Transition 2: call_AAA_Server
  // Function call: call_AAA_Server (TODO: implement logic)
  [] s_System=2 ->
    (s_System' = 3);

  // Terminal state (self-loop)
  [] s_System=4 -> (s_System' = 4);

endmodule
// ===== Intruder/Attacker Model (Optional) =====
// TODO: Add Dolev-Yao intruder model for security analysis
// module Intruder
//   // Attacker can intercept, forge, and replay messages
// endmodule

// ===== Labels for Properties =====
// Define observable states for verification
label "error" = false;  // TODO: Define error condition
label "auth_success" = s_SmartObject=9 & s_Controller=16 & s_AAA_Server=6 & s_System=3;
label "deadlock" = s_SmartObject=10 | s_Controller=17 | s_AAA_Server=7 | s_System=4;

// ===== Rewards (Optional) =====
// rewards "message_cost"
//   [sync_ComSC_*] true : 1;  // Cost per message
// endrewards

// ===== Notes for Manual Refinement =====
// 1. Function calls (call_*) are placeholders - implement crypto logic
// 2. Add probabilistic channel model (message loss, corruption)
// 3. Implement Dolev-Yao intruder if security analysis required
// 4. Define specific error conditions in "error" label
// 5. Add reward structures for performance metrics