// ===================================================
// Enhanced PRISM MDP Model (Generated by pat2prism)
// Optimized for Security Protocol Verification
// ===================================================

mdp

// ===== Configuration Parameters =====
const double p_flip = 0.02;  // Channel error probability
const int MAX_NONCE = 10000;

// ===== Message Type Encoding =====
// Maps message names to integer indices for channel variables
const int MSG_NO_MSG = 0;  // NO_MSG
const int MSG_LO_CoAP_POST = 1;  // LO_CoAP_POST
const int MSG_EAP_Request_PSK_M1 = 2;  // EAP_Request_PSK_M1

// ===== Global Variables =====
// Protocol variables (from PAT declarations)
global EAP_Request_PSK_M1 : [0..2] init 0  // EAP_Request_PSK_M1, EAP_Response_PSK_M2, LO_CoAP_POST;
global PSK : [0..10000] init 1234;
global ID_P : [0..10000] init 1;
global LO_CoAP_POST_ID_P_1 : [0..100] init 0  // ID field;
global LO_CoAP_POST_ID_P : [0..100] init 0  // ID field;

// Channel variables (one per channel)
global chan_ComSC : [0..2] init 0;  // Channel ComSC
global chan_ComCA : [0..2] init 0;  // Channel ComCA

// ===== Process Modules =====
// Process: SmartObject
module SmartObject
  // State variable for SmartObject
  s_SmartObject : [0..3] init 0;

  // Transition 0: sync_ComSC_LO_CoAP_POST
  // Synchronized action: sync_ComSC_LO_CoAP_POST
  [sync_ComSC_LO_CoAP_POST] s_SmartObject=0 ->
    (LO_CoAP_POST_ID_P' = ID_P) &
    (chan_ComSC' = MSG_LO_CoAP_POST) &
    (s_SmartObject' = 1);

  // Transition 1: sync_ComSC_EAP_Request_PSK_M1
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M1
  [sync_ComSC_EAP_Request_PSK_M1] s_SmartObject=1 ->
    (chan_ComSC' = MSG_EAP_Request_PSK_M1) &
    (s_SmartObject' = 2);

  // Terminal state (self-loop)
  [] s_SmartObject=3 -> (s_SmartObject' = 3);

endmodule
// Process: Controller
module Controller
  // State variable for Controller
  s_Controller : [0..3] init 0;

  // Transition 0: sync_ComSC_LO_CoAP_POST
  // Synchronized action: sync_ComSC_LO_CoAP_POST
  [sync_ComSC_LO_CoAP_POST] s_Controller=0 ->
    (ID_P_1' = LO_CoAP_POST_ID_P_1) &
    (chan_ComSC' = MSG_LO_CoAP_POST) &
    (s_Controller' = 1);

  // Transition 1: sync_ComSC_EAP_Request_PSK_M1
  // Synchronized action: sync_ComSC_EAP_Request_PSK_M1
  [sync_ComSC_EAP_Request_PSK_M1] s_Controller=1 ->
    (chan_ComSC' = MSG_EAP_Request_PSK_M1) &
    (s_Controller' = 2);

  // Terminal state (self-loop)
  [] s_Controller=3 -> (s_Controller' = 3);

endmodule
// Process: System
module System
  // State variable for System
  s_System : [0..3] init 0;

  // Transition 0: call_SmartObject
  // Function call: call_SmartObject (TODO: implement logic)
  [] s_System=0 ->
    (s_System' = 1);

  // Transition 1: call_Controller
  // Function call: call_Controller (TODO: implement logic)
  [] s_System=1 ->
    (s_System' = 2);

  // Terminal state (self-loop)
  [] s_System=3 -> (s_System' = 3);

endmodule
// ===== Intruder/Attacker Model (Optional) =====
// TODO: Add Dolev-Yao intruder model for security analysis
// module Intruder
//   // Attacker can intercept, forge, and replay messages
// endmodule

// ===== Labels for Properties =====
// Define observable states for verification
label "error" = false;  // TODO: Define error condition
label "auth_success" = s_SmartObject=2 & s_Controller=2 & s_System=2;
label "deadlock" = s_SmartObject=3 | s_Controller=3 | s_System=3;

// ===== Rewards (Optional) =====
// rewards "message_cost"
//   [sync_ComSC_*] true : 1;  // Cost per message
// endrewards

// ===== Notes for Manual Refinement =====
// 1. Function calls (call_*) are placeholders - implement crypto logic
// 2. Add probabilistic channel model (message loss, corruption)
// 3. Implement Dolev-Yao intruder if security analysis required
// 4. Define specific error conditions in "error" label
// 5. Add reward structures for performance metrics